// flock-web/src/lib/components/PostComponent.svelte
<script lang="ts">
    import type { Post } from '@buf/wcygan_flock.bufbuild_es/backend/v1/post_pb';
  
    export let post: Post;
  
    function formatDate(timestamp: bigint): string {
      return new Date(Number(timestamp)).toLocaleString();
    }
  
    function getInitial(name: string | undefined | null): string {
      return (name || '').charAt(0).toUpperCase() || '?';
    }
  
    $: profileColor = post.author?.profilePicture?.pictureType?.case === 'hexColor'
      ? post.author.profilePicture.pictureType.value
      : '#CBD5E1';
  </script>
  
  <div class="border rounded-lg p-4 bg-white shadow hover:shadow-md transition-shadow">
    <div class="flex items-center gap-3 mb-2">
      <div
        class="w-10 h-10 rounded-full flex items-center justify-center text-white text-lg font-semibold"
        style:background-color={profileColor}
      >
        {getInitial(post.author?.firstName) || getInitial(post.author?.username)}
      </div>
      <div>
        <div class="font-semibold">
          {#if post.author?.firstName || post.author?.lastName}
            {post.author.firstName} {post.author.lastName}
          {/if}
          <span class="text-gray-500 font-normal">@{post.author?.username || 'unknown'}</span>
        </div>
        <div class="text-sm text-gray-500">{formatDate(post.createdAt)}</div>
      </div>
    </div>
    <p class="text-gray-800 whitespace-pre-wrap">{post.content}</p>
  </div>

// flock-web/src/components/PostComponent.tsx
'use client';

import Link from 'next/link';
import type { Post } from '@/lib/api';
import { Heart, MessageCircle, Share2 } from 'lucide-react';

interface Props {
  post: Post;
}

export default function PostComponent({ post }: Props) {
  return (
    <article className="border-b p-4 hover:bg-gray-50 transition-colors">
      <div className="flex gap-3">
        <div className="flex-shrink-0">
          <div
            className="w-12 h-12 rounded-full"
            style={{
              backgroundColor: post.author?.profilePicture?.pictureType.case === 'hexColor'
                ? post.author.profilePicture.pictureType.value
                : '#ccc'
            }}
          />
        </div>

        <div className="flex-grow">
          <div className="flex items-center gap-1">
            <Link
              href={`/profile/${post.author?.username}`}
              className="font-semibold hover:underline"
            >
              {post.author?.firstName} {post.author?.lastName}
            </Link>
            <span className="text-gray-500">·</span>
            <Link
              href={`/profile/${post.author?.username}`}
              className="text-gray-500 hover:underline"
            >
              @{post.author?.username}
            </Link>
            <span className="text-gray-500">·</span>
            <span className="text-gray-500">
              {new Date(Number(post.createdAt)).toLocaleDateString()}
            </span>
          </div>

          <p className="mt-2 whitespace-pre-wrap">{post.content}</p>

          <div className="flex gap-6 mt-3">
            <button className="flex items-center gap-2 text-gray-500 hover:text-red-500 transition-colors">
              <Heart className="w-5 h-5" />
              <span>0</span>
            </button>
            <button className="flex items-center gap-2 text-gray-500 hover:text-blue-500 transition-colors">
              <MessageCircle className="w-5 h-5" />
              <span>0</span>
            </button>
            <button className="flex items-center gap-2 text-gray-500 hover:text-green-500 transition-colors">
              <Share2 className="w-5 h-5" />
              <span>0</span>
            </button>
          </div>
        </div>
      </div>
    </article>
  );
}
